### ISSUE TITLE
Coloring nodes based on specific functions

### ISSUE THREAD

**Issue by cmottac** [scikit-tda/kepler-mapper#140]
I'm getting frustrated because I would like to color the graph nodes based on some functions, using the visualize() function. Take the example of the breast cancer, suppose I want to color the nodes based on the average value of y (our target value). How can I do it?

Also, is there any functionality to automatically detect flares?

Thank you in advance and congratulation for this great project!

**Comment by sauln** [comment]
I've added some more [documentation here](https://kepler-mapper.scikit-tda.org/reference/stubs/kmapper.KeplerMapper.html#kmapper.KeplerMapper.visualize).

The `color_function` is a little confusing in name, it's not actually a function, but the 1d image of a function applied to the data. Let me know if the examples of using the `color_function` help you, or if there are still pain points.

re: detecting flares. This is a hard problem. I've been working on an implementation of extended persistence, which might help, but there isn't really any great theory for doing this.

**Comment by carlomotta** [comment]
Thank you very much, it is definitely clear now.

Re detecting flares: that sounds interesting, may I know more about it?

Kind regards,
Carlo

**Comment by sauln** [comment]
The chapter on extended persistence can be found here: https://www2.cs.duke.edu/courses/fall06/cps296.1/Lectures/sec-VI-4.pdf. 

I've found that the Cohen-Steiner paper is very helpful as well. I think it was a Curry paper or slides I saw mention that detecting flares can be done through extended persistence. Haven't found an example or implementation of this though.

**Comment by emerson-escolar** [comment]
I was reading Lum, et al. "Extracting insights from the shape of complex data using topology" recently and saw that they describe a "flare detection algorithm" in the Methods section that seems to use only classical persistence. Haven't really read the algorithm in detail yet, and don't know if this is relevant.
