### ISSUE TITLE
Is there a way to fix the display orientation of the topological graph in the html file?

### ISSUE THREAD

**Issue by karinsasaki** [scikit-tda/kepler-mapper#144]
I want to save different images (different colourings) of the same graph, to visualise colouring by feature. (I am using mapper.visualize not plotliviz.)

Making comparisons is difficult if the graph is oriented differently in every image (see image below).

![feature colouring 1](https://user-images.githubusercontent.com/18656780/53729518-bdec8180-3e75-11e9-95a4-daa5d31fa98c.png)
![feature colouring 2](https://user-images.githubusercontent.com/18656780/53729520-bdec8180-3e75-11e9-922b-c2e8e3db70e4.png)

I could pull the vertices around (with the pointer) until I get similar positions, but this is not efficient if I have many graphs. I am wondering if there is a non-manual way for orienting the graph? 

Thank you!

**Comment by sauln** [comment]
At the moment, no. The best method for doing this would be to use the plotlyviz, or networkx adapter to build a static layout of the graph.

@mlwave is prototyping an implementation to toggle between multiple coloring functions. This would let you pull the graph around to find one layout, then switch the colorings once it's set. It should hopefully be integrated soon.

One potential solution would be to allow users to specify the initial graph layout in the `visualize` method. I haven't touched the layout code in a while, but I think this wouldn't be too hard the thread through.
