### ISSUE TITLE
Affiliation missing for Sam Mangham (JOSS paper)

### ISSUE THREAD

**Issue by leouieda** [scikit-tda/kepler-mapper#147]
The affiliation index for Sam Mangham is marked as `4` but there is no definition of an index 4 affiliation below it.

openjournals/joss-reviews#1315

**Comment by sauln** [comment]
@smangham What would you like your affiliation to be?

**Comment by smangham** [comment]
Could my affiliation be 'Department of Electronics & Computer Science, University of Southampton, Southampton, SO17 1BJ, UK' please! My paper name is usually 'S. W. Mangham' or 'Sam W. Mangham', whichever fits your style.
