### ISSUE TITLE
more info on build_histogram todo?

### ISSUE THREAD

**Issue by deargle** [scikit-tda/kepler-mapper#150]
What is the "normal" build_histogram function that the following is referring to? https://github.com/scikit-tda/kepler-mapper/blob/2c2890fe4a98badcc029dcd8b8689c014ae5fe3d/kmapper/visuals.py#L219

**Comment by sauln** [comment]
I think this todo is old. At one point there was a build_histogram function for the html vis and one for the plotly vis.
