### ISSUE TITLE
Plotlyviz not working in jupyter notebook

### ISSUE THREAD

**Issue by asdspal** [scikit-tda/kepler-mapper#151]
I'm trying the circle example in the jupyter notebook using the [examples notebook](https://github.com/scikit-tda/kepler-mapper/blob/master/examples/makecircles/make-circles-with-plotly.ipynb). I haven't changed anything in the notebook. All the cells run without error, but I don't get a visualization output(or any output ) from the last cell. Also, my bash shell running jupyter notebook doesn't show any error or message.

OS: ubuntu-16.04
python: 3.6.7
python-packages:-
kmapper:  1.2.0
plotly: 3.7.0
python-igraph: 0.7.1
networkx: 2.2
ipywidgets: 7.4.2
notebook: 5.7.6

What should I do? Where  should I look for errors?

**Comment by sauln** [comment]
Hmm, that's weird. I would try resetting the kernel.  

After that, I would look at the console log to see if there are any errors there. You can do this by right-clicking, selecting "Inspect element". In most browsers, it will open up a developer pane showing you the raw HTML. there should then be a tab that says "Console" which will show any errors.

**Comment by deargle** [comment]
Doesn't that example only appear if run from within a jupyter notebook unless you add an option to save to png? I remember having to install a jupyter plugin to spyder to be able to run it.

**Comment by asdspal** [comment]
Thanks for pointing me in the right direction. I checked the browser's dev console and found that plotlywidget is missing. I installed the plotlywidget and it's working now.
