### ISSUE TITLE
Target space of lens function something other than R?

### ISSUE THREAD

**Issue by karinsasaki** [scikit-tda/kepler-mapper#159]
The mapper algorithm starts with a real valued function f:X->R, where X is the data set and R is 1d Euclidean space. 

According to the original paper, the target space of the lenses (called filters in the paper) may be Euclidean space, but it might also be a circle, a torus, a tree or another metric space. 

My question is whether with the Kepler Mapper we can implement the mapper algorithm with the target space being, e.g. a circle (the simplest next case after R)?

[
According to the paper, the way this is done (if I understood correctly the introduction of the paper where they allude to this) is by mapping the topological graph generated to the desired target space. I am not sure if I understand exactly what this means...
]

Thanks for any help!

**Comment by sauln** [comment]
You could define your lens however you want. The hard part will be coming up with a suitable cover. You would probably have to implement your own cover class for each of these particular shapes.

**Comment by karinsasaki** [comment]
Ah ok. I understand - I did think that writing the lens was not the issue... 
Just one final question - from your intuition, do you think mapping to, say S1 (circle) would force the mapper the "find" circles in the data set? and is doing that somehow biasing what you see after you apply the mapper?

**Comment by sauln** [comment]
I don't think you would necessarily find more circles. You should have a pretty good reason for mapping to a circle though. For instance, if you were studying data on planet Pacman, it would make sense to map to a torus.  If you didn't, I could imagine your conclusions could turn out very differently.
