### ISSUE TITLE
What is the meaning of colors?

### ISSUE THREAD

**Issue by larionov-s** [scikit-tda/kepler-mapper#160]
Hello, 
What is the meaning of colors in the visualization? Can you please update documentation with it?
Thanks!

**Comment by karinsasaki** [comment]
Could you provide the code of what you are trying to do? Your question is not clear.

The `visualize`  function has a parameter `color_function` and the documentation says the following:

`color_function : list or 1d array
            A 1d vector with length equal to number of data points used to build Mapper. Each value should correspond to a value for each data point and color of node is computed as the average value for members in a node.
`

**Comment by larionov-s** [comment]
If I don't provide color_function, it still assigns a color. Does it have any meaning?

**Comment by deargle** [comment]
By default, it colors by row number.

**Comment by MLWave** [comment]
Thanks for helping @karinsasaki and @deargle .
