### ISSUE TITLE
Are there issues running keppler-mapper on Windows?

### ISSUE THREAD

**Issue by karinsasaki** [scikit-tda/kepler-mapper#161]
I have a Mac and I have shared a jupyter notebook of my work with kmapper, with a colleague who has a Windows machine. 

He does not edit the code in any way and the data set is the same.

We both installed KMapper as per the instructions

When he runs the notebook, he doesn't get any errors, but the output of the mapper (the topological network) is not the same as what is generated when I run it on my machine. We initially saw this when we visualised the html file generated with the visualize function.

I have actually reduced the issue to the map function of kmapper - I have counted the number of connected component and vertices of the topological networks generated and they are distinct.

I am including here the image of what "is correct" (from the Mac):
![Screen Shot 2019-04-04 at 13 10 34](https://user-images.githubusercontent.com/18656780/55551501-40699a80-56db-11e9-9b66-14944cd5681e.png)

and the image of what "is wrong" (from the Windows):
![Screen Shot 2019-04-04 at 13 09 42](https://user-images.githubusercontent.com/18656780/55551500-40699a80-56db-11e9-82e9-8b93a8ff2a1c.png)

I am unsure why we are getting different results. So I am wondering if you have come across other people having issues with using kmapper on Windows?

THanks!

**Comment by sauln** [comment]
Hi, Thanks for reaching out. I'm sorry you're having this issue. 

We haven't heard of any problems on Windows, but I can't think of any reason why there should be problems.

Could you supply version information for all the dependencies for both the Mac and Windows setup. My best guess is that the dependency is out of date on either the windows or mac. The most recent version did fix a bug in the way the cover is calculated, so the % overlap needs to be reduced in the new version. This could cause the problem you're seeing.

**Comment by karinsasaki** [comment]
Thanks for the info.

The release file I have on the version installed on the Mac says:
`Alpha
1.1.6 (Nov 8, 2018)
`
Which seems to be the same version as that in this GitHub repo (from reading the [release file](https://github.com/scikit-tda/kepler-mapper/blob/master/RELEASE.txt)).

The version installed on the Windows is the most recent one (1.2.0 I think) which you can get using `pip install kmapper` as instructed in [here](https://kepler-mapper.scikit-tda.org). 

Could you confirm this could be the source of the problem, and I guess more importantly, if there are any other major issues on the 1.1.6 version? Perhaps there is somewhere where I can read the changes that have been made between 1.1.6 and 1.2.0?

Many thanks!

**Comment by sauln** [comment]
Sorry, I always forget to update the release file. It has been updated to reflect the [github release](https://github.com/scikit-tda/kepler-mapper/releases/tag/1.2.0) and [pypi release](https://pypi.org/project/kmapper/1.2.0/). 

The main change is that the old way of computing the cover was a little strange and the value for percent overlap did not match peoples intuition. The result of updating is that you should decrease the value by about half.  

Issue #125 prompted the update.

**Comment by karinsasaki** [comment]
Thank you! Panic over! 

Halving the percentage overlap did give a more reasonable image but it was not the exact same as we obtained with the older version of kmapper. So I ran again a parameter value grid search and I noticed  that to find a similar graph, the number of intervals and the eps value I was using for the clusterer (DBSCAN) also changed slightly. I am sorry I can't be more specific than that... 

Thanks again !

**Comment by deargle** [comment]
I'm interested in your grid search approach -- for each setting
permutation, are you generating one visualization, leaving you with dozens
of visualizations to manually compare? Or are you evaluating some metric on
the complex for each setting permutation?

**Comment by sauln** [comment]
@karinsasaki sorry, it will probably not be possible to reconstruct the original cover exactly. If you need to recreate the one you've found, you could make sure to use version 1.1.6.

**Comment by karinsasaki** [comment]
@sauln ok. I understand. THanks!

@deargle to answer your question succinctly, the metric I am using is the number of connected components and then using the smallest values found for the parameters.

In more detail, I am interested only in topological graphs that consist of one connected component, so using the code below I count the number of components of the simplicial complexes that are generated using the kmapper during the parameter value grid search, and only save the parameter values of those with one connected component; I save them in a data frame. I then sort the values of the data frame by the  eps (a parameter in the clustering algorithm I am using - DBSCAN) and by the percentage overlap of each of the lenses (because higher values give a more interconnected graph, so I want the smallest possible), from small to large. Finally I generate the images of the simplicial complexes and choose the ones that I feel give me a more intuitive view of the data.

You could be as creative as you like with the metrics you choose to evaluate your simplicial complexes, e.g. number of edges, number of vertices, connectivity, regularity, completeness, lengths of paths, presence of cycles, regional density, etc

```
# Python program to print connected components in an undirected graph 
# Reference: https://www.geeksforgeeks.org/connected-components-in-an-undirected-graph/

class Graph: 
    
    # init function to declare class variables 
    def __init__(self,V): 
        self.V = V 
        self.adj = [[] for i in range(V)] 

    def DFSUtil(self, temp, v, visited): 

        # Mark the current vertex as visited 
        visited[v] = True

        # Store the vertex to list 
        temp.append(v) 

        # Repeat for all vertices adjacent 
        # to this vertex v 
        for i in self.adj[v]: 
            if visited[i] == False: 
                
                # Update the list 
                temp = self.DFSUtil(temp, i, visited) 
        return temp 

    # method to add an undirected edge 
    def addEdge(self, v, w): 
        self.adj[v].append(w) 
        self.adj[w].append(v) 

    # Method to retrieve connected components 
    # in an undirected graph 
    def connectedComponents(self): 
        visited = [] 
        cc = [] 
        for i in range(self.V): 
            visited.append(False) 
        for v in range(self.V): 
            if visited[v] == False: 
                temp = [] 
                cc.append(self.DFSUtil(temp, v, visited)) 
        return cc 

# Python program to count the number of connected components of a simplicial complex generated using Kepler Mapper
def count_connected_components(simplicial_complex):
    """
    Description:
        Count the number of connected components of a simplicial complex.
    Input arguments:
        simplicial_complex: output from the Keppler-Mapper map function
    Output variables:
        n_v: total number of vertices of the topological graph
        n_cc: total number of connected components of the topological graph
    """
    
    # nodes of simplicial_complex
    nodes = dict([(y,x) for x,y in enumerate(sorted(set(simplicial_complex['nodes'])))])

    # simplicial complex as a graph
    g = Graph(len(simplicial_complex['nodes'])); 

    for val in simplicial_complex['links']:
        l = len(simplicial_complex['links'][val])
        for i in np.arange(l):
            g.addEdge(nodes[val], nodes[simplicial_complex['links'][val][i]]) 

    # number of connected components
    n_v = len(nodes)
    n_cc = len(g.connectedComponents() )        
    
    return(n_v, n_cc)
```
