### ISSUE TITLE
Make keppler-mapper sparse compatible

### ISSUE THREAD

**Issue by retdop** [scikit-tda/kepler-mapper#162]
I recently tried to use the Mapper algorithm for a graph with more than 1 million nodes. I, thus computed the adjacency matrix with the scipy sparse CSR format, which drastically reduces the memory usage.

However keppler-mapper does not currently work with sparse matrices. 

I successfully modified a few lines and created a sparse-compatible version.

Would that be of interest to you for a pull request?

**Comment by deargle** [comment]
That's funny, I did similarly a few days ago. I'd be interested to see your approach.

**Comment by sauln** [comment]
Yes! We would love to incorporate the changes.  Please submit a PR. 

Thank you!
