### ISSUE TITLE
Remove mutable arguments

### ISSUE THREAD

**Issue by sauln** [scikit-tda/kepler-mapper#165]
As mentioned in openjournals/joss-reviews#1315, some functions have mutable arguments.

I found the following instances of this:
https://github.com/scikit-tda/kepler-mapper/blob/8a2a955e2b7302ee3c37e5c6a2c6ebfc1924a39b/kmapper/kmapper.py#L630-L632

These could easily be transformed into something like
```
def f(param=None):
    param = [] if param is None else param
```

**Comment by cmorph1** [comment]
Hi @sauln 
I'm new to os, but I'd like to take a look at this

**Comment by sauln** [comment]
Yeah, absolutely! Let me know how I can support you!

**Comment by cmorph1** [comment]
Excellent, leave this with me. I'll come back to you if I get stuck.

**Comment by leouieda** [comment]
I would add to be wary of dictionaries and non-builtin types (like instances of your own classes) as well.

**Comment by sauln** [comment]
#167 fixes most of the occurrences of mutable arguments. I can't find any dictionaries and all that is left is some non-builtin types.

I'm hesitant to change the instances when it's our class or a sklearn class. For one, I like how [they are rendered in the documentation](https://kepler-mapper.scikit-tda.org/reference/stubs/kmapper.KeplerMapper.html#kmapper.KeplerMapper.map) and I'm not sure how to best convey the defaults when `cover=None`. They also all have a `fit` method that is called within the function, so we can be sure the objects aren't being fit to the wrong data.

@leouieda, if you're steadfast on these non-builtin types, we can figure out how to remove them without compromising the documentation.

**Comment by leouieda** [comment]
@sauln I understand your points and have struggled with that myself. The main problem is that the default arguments are instantiated at import time. So calling `fit` the default argument will have side effects on other instances. For example:

```python
class Estimator:
    def __init__(self):
        self.params_ = None    
    def fit(self, X, y):
        self.params_ = [X, y]
        return self
    
class OtherEstimator:
    def __init__(self, estimator=Estimator()):
        self.estimator = estimator        
    def fit(self, X, y):
        self.estimator.fit(X, y)
        return self

a = OtherEstimator()
b = OtherEstimator()

a.fit(1, 2)

a.estimator is b.estimator
# True

print(a.estimator.params_)
# [1, 2]

print(b.estimator.params_)
# [1, 2]
```

This can lead to nasty bugs. It's convenient for the docs but I don't think the trade-off is worth it.

If you look at the scikit-learn defaults and other core Python libraries, you'll see some different strategies for dealing with this. Many packages default to `None` if want an empty container or a string if there are many options with names. See `cmap="viridis"` in matplotlib or the [`cv` argument in `cross_val_score`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html#sklearn.model_selection.cross_val_score).
That is certainly the approach I'd recommend.
