### ISSUE TITLE
Ayasdi's Neighborhood Lens 1 and 2?

### ISSUE THREAD

**Issue by karinsasaki** [scikit-tda/kepler-mapper#169]
I feel embarrassed asking this here and if it's not appropriate then please delete, but I have not been able to find the answer anywhere...

(Some of ?) the lenses that Ayasdi uses are listed in [this](https://platform.ayasdi.com/sdkdocs/userdoc/lenses_supp_overview.html) page (scroll to the bottom of the page). The names are self-explanatory, except for the Neighborhood Lens 1 and Neighborhood Lens 2. 

Does anyone know exactly what the maps are to define those two lenses? One possibility I can think of  is the distance to the first and the second nearest neighbors, for the choice of metric. Does this sound reasonable?

Unfortunately for me, two papers I am reading used Ayasdi and these lenses for their analysis, but of course they did not explain what they are (and to learn about them you have to be able to log into Ayasdi (at a price of $100k/year...))

Many thanks

**Comment by sauln** [comment]
🤷‍♂️ Your guess makes as much sense as anything I can think of. 

I would try reaching out to the authors of those papers.

**Comment by karinsasaki** [comment]
I did - no reply...
Thanks!

**Comment by sauln** [comment]
Okay, I'm closing the issue.  If you do find out what they are, please do share.  

Thank you.

**Comment by ejmolinelli** [comment]
@karinsasaki Hey, I had the same question. I'm really shocked that nature allows authors to report only software parameters to proprietary software in the 'methods' section.  

Anyway, the best explanation I could find for the neighborhood lens is found in this paper
[https://www.sciencedirect.com/science/article/abs/pii/S0003267017313077](https://www.sciencedirect.com/science/article/abs/pii/S0003267017313077)

I hope it helps.
