### ISSUE TITLE
Error --module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

### ISSUE THREAD

**Issue by mlnjsh** [scikit-tda/kepler-mapper#170]
I m running the following code from Brest cancer example 
import sys
try:
    import pandas as pd
except ImportError as e:
    print("pandas is required for this example. Please install with conda or pip  and then try again.")
    sys.exit()

import numpy as np
import sklearn
from sklearn import ensemble
import kmapper as km
from kmapper.plotlyviz import *

import warnings
warnings.filterwarnings("ignore")

getting error 
module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

**Comment by MLWave** [comment]
try:

`pip install pandas`

and run again.
