### ISSUE TITLE
digitize edge

### ISSUE THREAD

**Issue by wjdrlduq1234** [scikit-tda/kepler-mapper#175]
Hello, I using your package kmapper.
I'd like to propose a module 'digitize_edge()'.

If end kmapper.KeplerMapper.visualize(), we can use kmapper.KeplerMapper.digitize_edge().
digitize_edge() print out a Dataframe. 

Before understanding the Dataframe, I'd like to define 'path length'.
path length is the length between two nodes. If two nodes are same cluster, then path length is 0. And if two nodes are not connected by a edge, then it's path length is -1. further on, if two nodes are connected indirectly by x edge, then it's path length is x.

Now I can explain the Dataframe.
index of the Dataframe, is same input Dataframe. and columns too.
So if I input Dataframe number of index is 20, digitize_edge()'s Dataframe is 20*20=400.
And the Dataframe filled 'path length' with all index.

In my opinion, for many input data(and same index), if skip visualize and print digitize_edge()'s Dataframe,
we can analysis that a change in relations.

Thanks for your package. I expect next update.

**Comment by sauln** [comment]
Hi, it sounds like it could be a useful function. If you’d like to write it and submit a pull request, we can incorporate it into the library.

**Comment by wjdrlduq1234** [comment]
Thanks! As soon as possible, I'd like to write it and submit a pull request.
And there is one more function in below page.

![12](https://user-images.githubusercontent.com/50209510/61047819-4ded9980-a41b-11e9-96ae-961b28549e6e.PNG)

When I input come x in node y, then node y glow.
Maybe it help you find x quickly!

**Comment by sauln** [comment]
That sounds great! I look forward to the PR

**Comment by wjdrlduq1234** [comment]
https://github.com/wjdrlduq1234/kepler-mapper/pull/1/files

Hello, Long time no see!
I upload code half-proceeded.
I made it as simple as I could.
If you have any feedback, please let me know.

I'm in trouble how to obtain path length more than 2.
I've been thinking about it over and over.

Thanks!

**Comment by sauln** [comment]
It might be possible to use something like [`all_nearest_neighbors` from networkx](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.generic.all_shortest_paths.html#networkx.algorithms.shortest_paths.generic.all_shortest_paths). That could be pretty slow though.  There might be faster alternatives out there?

**Comment by wjdrlduq1234** [comment]
I'm taking a closer look at the modules sent.
I think that module is available.
But when it comes to speed, there's nothing I can say yet.
I'll try a few things and talk to you.

**Comment by wjdrlduq1234** [comment]
https://github.com/wjdrlduq1234/kepler-mapper/pull/1/files#diff-5620fa6810a65f6e0ed41c79d4b5b3c6

I decided not to use mine complex algorithms.
Instead, I used the module you sent me, and I think I succeeded.
Even the speed has gone very fast.
Please review the code. And if you have any feedback, please let me know.


If this is settled, I want to tell you a new story.
In fact, I wrote a paper using your package; kmapper.
In my opinion, results vary depending on how they are projected and clustered.
So the following algorithm is proposed

**Existing algorithm that I understand)**

> 1. projecting
> 2. clustering
> 3. mapping
> 4. visualization 3

**proposing algorithm)**

> 1'. projecting
> 2'. clustering
> 3'. mapping x times in different ways.
> 4'. using digitize_relationship x times each mapped from 3'.
> 5'. pooling results of 4'
> 6'. visualization 5'

I think it will be useful for people who need to show only one result.

**Comment by wjdrlduq1234** [comment]
Oh.. I'm really sorry. 
This is first time that I PR.
I just realized that I had to add to your PR.
I apologize if it seemed rude.
I'm learning how to do PR.

**Comment by wjdrlduq1234** [comment]
I've already submitted the completed code.
I made the example using iris data from sklearn. Here is the example code.
There seems to be something wrong with Gitbub. So I uploaded here.
After the problem is solved, I will add the code in PR

`from sklearn.datasets import load_iris
import kmapper as km
import pandas as pd

# Data setting
inverse_data = load_iris().get('data')
index = []
for name in load_iris().get('target_names'):
    for x in range(50):
        y = '%s_%s' % (name, x)
        index.append(y)
        
# creating graph
mapper = km.KeplerMapper(verbose=0)
projected_data = mapper.project(inverse_data, 
                                projection="knn_distance_2",
                                distance_matrix='euclidean')
graph = mapper.map(projected_data,
                   cover=km.Cover(n_cubes=3, perc_overlap=0.2))

# digitize_relationship
result = km.digitize_relationship(graph, index)
print(result)`

**Comment by wjdrlduq1234** [comment]
for name in load_iris().get('target_names'):
for x in range(50):
y = '%s_%s' % (name, x)
index.append(y)

creating graph
