### ISSUE TITLE
printing member_ids

### ISSUE THREAD

**Issue by mlnjsh** [scikit-tda/kepler-mapper#183]
Suppose i have the list
my_list=[{'id':0,'name':'cube0_cluster0','member_ids': [429, 432, 435]}, 
{'id': 1,'name': 'cube0_cluster1','member_ids': [0, 4, 5]}, 
{'id':0,'name':'cube1_cluster1','member_ids': [700, 706, 800]}]

I want to print all member_ids for cube{ }_cluster1

My expected output is to print [0,4,5] and [700,706,800]

**Comment by deargle** [comment]
A simple for loop printing member_ids? It's just a list of objects
