### ISSUE TITLE
Mismatch in the total number of samples 

### ISSUE THREAD

**Issue by andreacortis** [scikit-tda/kepler-mapper#205]
**Describe the bug**
I am having trouble with the number of samples in the output of `mapper`. 

My starting point is a `769x769` distance matrix, `D`.

```
In [107]: D.shape
Out[107]: (769, 769)
```
I then run,

```
import kmapper as km
mapper = km.KeplerMapper(verbose=2)
lens = mapper.fit_transform(D, distance_matrix=True)
clusterer=sklearn.cluster.DBSCAN(eps=1.1, min_samples=5, metric='precomputed')
cover = km.Cover(15, 0.3)
graph = mapper.map(lens, D, clusterer=clusterer, cover= cover, precomputed=True)
```

which produces

```
KeplerMapper(verbose=2)
..Composing projection pipeline of length 1:
	Projections: sum
	Distance matrices: True
	Scalers: MinMaxScaler()
..Projecting on data shaped (769, 769)

..Projecting data using: sum

..Scaling with: MinMaxScaler()

Mapping on data shaped (769, 769) using lens shaped (769, 1)
```

now, if I calculate the total number of points in the nodes I get:

```
In [114]: nodes = graph['nodes']
     ...: h = []
     ...: for k,v in graph['nodes'].items():
     ...:     h.extend(v)
     ...: print(f"total number of points in the graph {len(set(h))}")
total number of points in the graph 702
```

Note that 702 is also what is reported in the UI as the number of `unique samples`. I checked the samples in the original dataset and they are, however, all unique.

Why the number of points is 702 and not 769? Is the difference the set of isolated samples?

**Comment by deargle** [comment]
The graph only includes nodes that contain a minimum number of samples
(iirc, default right now is 2). Therefore, if a datapoint never clusters
with enough other points, it would not be retained in any node in the final
graph.

**Comment by andreacortis** [comment]
Thank you, that's what I suspected!
