### ISSUE TITLE
nr_cubes is unexpected argument in map()

### ISSUE THREAD

**Issue by yanuarkrisna** [scikit-tda/kepler-mapper#206]
why my python cant read nr_cubes?
![error1_tda](https://user-images.githubusercontent.com/47708439/103063571-51132000-45e4-11eb-8c17-bd0ad384aff1.png)

**Comment by sauln** [comment]
Newer versions of kepler mapper don't support `nr_cubes`. You can use the newer cover api instead or try pinning to an earlier version.

**Comment by yanuarkrisna** [comment]
How to get the earlier code?  :(

**Comment by sauln** [comment]
Our documentation states that `nr_cubes` was deprecated in version 1.1.6 (https://kepler-mapper.scikit-tda.org/reference/stubs/kmapper.KeplerMapper.html#kmapper.KeplerMapper.map).  You can install that version with
`pip install kmapper==1.1.6` and it should work okay for you.

**Comment by yanuarkrisna** [comment]
Thank you for ur answer... i'll try it
