### ISSUE TITLE
Examples, gallery not included in readthedocs build 

### ISSUE THREAD

**Issue by deargle** [scikit-tda/kepler-mapper#218]
Unless I'm overlooking them, I don't see any links to the files built with sphinx-gallery, like [this one](https://github.com/scikit-tda/kepler-mapper/blob/master/examples/breast-cancer/breast-cancer.html). Also, examples.rst isn't included in any doctree, which [kind of references the gallery build](https://github.com/scikit-tda/kepler-mapper/blob/master/docs/examples.rst), but only links to github. What's the intention for the examples?

**Comment by sauln** [comment]
They're definitely a mess right now.  Some were in the docs and some were not. 

Anything you want to do to improve this would be great! 🙇

**Comment by deargle** [comment]
Closed by #220
