### ISSUE TITLE
Please refer to igraph instead of python-igraph

### ISSUE THREAD

**Issue by szhorvat** [scikit-tda/kepler-mapper#249]
Could you please change the following references to `python-igraph` to say `igraph` instead?

https://github.com/search?q=repo%3Ascikit-tda%2Fkepler-mapper%20python-igraph&type=code

See https://github.com/igraph/python-igraph/issues/699 for details.

**Comment by catanzaromj** [comment]
@szhorvat Thanks for catching this! If you'd like to make the changes yourself, please fork the repo, commit the changes, and then open a PR based on that fork. If you need help with this, please let me know.

**Comment by szhorvat** [comment]
I'm quite overwhelmed right now, and won't have the time (as you can see there were lots of similar issues I opened). Keep in mind that python-igraph will eventually stop getting maintained (in favour of igraph).
