### ISSUE TITLE
Expand docs

### ISSUE THREAD

**Issue by sauln** [scikit-tda/kepler-mapper#29]
The README is getting very long and it would be nice to add more examples, tutorials, and guides.We could migrate most of the docs to another venue and leave the README as a short guide for setup and contribute instructions.I think to do this we could use [mkdocs](http://www.mkdocs.org/) to build the pages for us and publish the docs with ReadTheDocs

- [x] Deploy on gh-pages 
- [ ] documentation of past versions
- [ ] Tutorial on how to use KeplerMapper
- [x] Document covering schemes
- [x] Document nerve building schemes

**Comment by sauln** [comment]
I added a very basic mkdocs setup in the docs/ directory. I basically just split the readme up into a few different files.

**Comment by sauln** [comment]
@MLWave, I'd like to setup a readthedocs side for km so we have a platform besides just the readme. I think we could expand examples and tutorials and the readme is too long already. 

What do you think? Here is example of how I think it could all look: http://hdbscan.readthedocs.io/en/latest/

If you're interested in this, could you please enable the github readthedocs webhook http://docs.readthedocs.io/en/latest/webhooks.html#webhook-integrations

Otherwise, do you have other suggestions on where to put new docs?

**Comment by MLWave** [comment]
Could also be the wiki. I am fine with both, though thinking using a wiki lowers threshold for contributing.

**Comment by sauln** [comment]
The wiki could work. The downsides are that anyone could make any changes they want and

**Comment by MLWave** [comment]
I hadn't thought about that. I do like official docs. I'll look into enabling the webhook. Perhaps we can use the Wiki for more transitory / brainstorming ideas.

**Comment by sauln** [comment]
That’s actually a great idea! Having wiki for a forum for temporary ideas and brainstorming sounds perfect! Issues seem hard to keep multiple threads going inside.

(Sorry I had not finished that comment but accidentally sent it, can’t remember what else I had t say)

**Comment by sauln** [comment]
Where you able to turn on the webhook? Once it's on, I can set up the configs so the docs update.

**Comment by MLWave** [comment]
I think I enabled the webhook. 

http://keplermapper.readthedocs.io/en/latest/

**Comment by sauln** [comment]
I pushed #43 with the readme cut up into a few different pages.  I used pandoc to convert the markdown to rst, so it's not perfect. But it's up there! Check out the link you gave me.

**Comment by MLWave** [comment]
Made a working draft here: https://github.com/MLWave/kepler-mapper/wiki/Documentation for more extended user documentation.

**Comment by sauln** [comment]
The wiki docs look really good.  Sometime this summer, it would nice to integrate the wiki docs with the GitHub pages docs.  What are your thoughts on this?
