### ISSUE TITLE
A Gui version [Suggestion/Request]

### ISSUE THREAD

**Issue by ghost** [scikit-tda/kepler-mapper#78]
Thank you for your hard work, you are appreciated.
It would be great if you considered releasing a GUI for the kepler-mapper, in-which allowing the user to:
- Import data file (csv/ xlsx/ etc...)
- Choose multiple criteria
- Allow selecting multiple nodes via "lasso tool" or by color.
- Allow export whole visualized data, or partial based on selection.

I would be glad to donate to such project to bring it to life
Waiting for your reply

**Comment by sauln** [comment]
Hi @christophered, sorry for the delay in getting back to you.

I also think a robust GUI for kepler-mapper would be great! I'm not sure it's in scope for this project though. Right now, we don't have the bandwidth to support anything that requires a server, but some of the suggested ideas could be implemented in the interface we have now.  For instance, I really like your idea of using a lasso tool.  I am working on an implementation now, but it will probably be a while until it's integrated.

As for a full-blown GUI, I know of at least one other project working on a more robust tool that will integrate with kepler-mapper. Hopefully sometime around Fall there will be more news to share about that project. 

Your willingness to donate is exciting and highly encouraging! Thank you.

**Comment by srnk9f** [comment]
I am also very much interested in the GUI and willing to donate for such project.
Has there been any updates on this since last fall as mentioned earlier last year.
Thanks,

**Comment by sauln** [comment]
@srnk9f please reach out via email: nat@riverasaul.com

**Comment by srnk9f** [comment]
Thanks Nathan for getting back.
If possible can we have a quick call to discuss further..
Let me know.
Thanks,
Sri.

**Comment by sauln** [comment]
That sounds good. We can arrange off GitHub.
